
______Description_____________________________________________________________________________________________________
When I set a path to a checkpoint file different than "None" I get this error.
I know for sure that the checkpoint is alright (because I have been extracting features from it) and I really cannot understand where the problem is.



______ERROR_____________________________________________________________________________________________________

>>> ## export_gen_imgs_in_standalone_folder.main(args)
... train_mars_augm.main(args)
Train set size: 144884 images, 563 identities
INFO:tensorflow:Summary name conv1_1/Elu:0/activations is illegal; using conv1_1/Elu_0/activations instead.
INFO:tensorflow:Summary name conv1_2/Elu:0/activations is illegal; using conv1_2/Elu_0/activations instead.
INFO:tensorflow:Summary name conv2_1/1/Elu:0/activations is illegal; using conv2_1/1/Elu_0/activations instead.
INFO:tensorflow:Summary name conv2_3/1/Elu:0/activations is illegal; using conv2_3/1/Elu_0/activations instead.
INFO:tensorflow:Summary name conv3_1/1/Elu:0/activations is illegal; using conv3_1/1/Elu_0/activations instead.
INFO:tensorflow:Summary name conv3_3/1/Elu:0/activations is illegal; using conv3_3/1/Elu_0/activations instead.
INFO:tensorflow:Summary name conv4_1/1/Elu:0/activations is illegal; using conv4_1/1/Elu_0/activations instead.
INFO:tensorflow:Summary name conv4_3/1/Elu:0/activations is illegal; using conv4_3/1/Elu_0/activations instead.
('feature dimensionality: ', 128)
WARNING:tensorflow:From train_app.py:641: sparse_softmax_cross_entropy (from tensorflow.contrib.losses.python.losses.loss_ops) is deprecated and will be removed after 2016-12-30.
Instructions for updating:
Use tf.losses.sparse_softmax_cross_entropy instead. Note that the order of the logits and labels arguments has been changed.
WARNING:tensorflow:From /home/ale/tensorflow/local/lib/python2.7/site-packages/tensorflow/contrib/losses/python/losses/loss_ops.py:434: compute_weighted_loss (from tensorflow.contrib.losses.python.losses.loss_ops) is deprecated and will be removed after 2016-12-30.
Instructions for updating:
Use tf.losses.compute_weighted_loss instead.
WARNING:tensorflow:From /home/ale/tensorflow/local/lib/python2.7/site-packages/tensorflow/contrib/losses/python/losses/loss_ops.py:151: add_loss (from tensorflow.contrib.losses.python.losses.loss_ops) is deprecated and will be removed after 2016-12-30.
Instructions for updating:
Use tf.losses.add_loss instead.
INFO:tensorflow:Summary name classification accuracy is illegal; using classification_accuracy instead.
INFO:tensorflow:Summary name mean squared feature norm is illegal; using mean_squared_feature_norm instead.
INFO:tensorflow:Summary name mean feature distance is illegal; using mean_feature_distance instead.
INFO:tensorflow:Summary name mean positive distance is illegal; using mean_positive_distance instead.
INFO:tensorflow:Summary name mean negative distance is illegal; using mean_negative_distance instead.
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "train_mars_augm.py", line 69, in main
    num_images_per_id=4, image_shape=IMAGE_SHAPE, trainable_scopes=args.trainable_scopes, **train_kwargs)
  File "train_app.py", line 225, in train_loop
    save_interval_secs=save_interval_secs, number_of_steps=number_of_steps)
  File "queued_trainer.py", line 390, in run
    restore_path, variables_to_restore)
  File "/home/ale/tensorflow/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 583, in assign_from_checkpoint
    raise ValueError(log_str)
ValueError: Checkpoint is missing variable [RMSprop_1/iterations]
>>> 
